* moultcaRds

** Description

*moultcaRds* is an R package for summarising, analysing and plotting
bird moult card data.

The package is aimed at field moult cards and feather-level moult records.
It provides simple tools to visualise moult extent in wing and tail diagrams.

** Main aims

- Store moult card data in a consistent format than can be easily ported to other related R packages.
- Summarise moult extension by feather tracts andor individual feathers.
- Plot schematic moult extent figures based on Jenni & Winkler book {cite}.
- Prepare moult records for further analysis.
- Keep dependencies minimal (~grid~ es un paquete que se instala junto con R).

** Installation
(not functional yet)

#+begin_src R
## development version
remotes::install_github("farcego/moultcaRds")
#+end_src


** Scripts

*** colSc.R
defines an internal helper that converts normalized moult scores (0–1)
into grey-scale colours for plotting feathers. Darker shades represent
more advanced moult.




** License

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or any
later version.
